[project]
name = "gufi-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "raykpridgen", email = "rkpridgen@coastal.edu" }
]
requires-python = ">=3.14"
dependencies = [
    "load-dotenv>=0.1.0",
    "matplotlib>=3.0.0",
    "mcp[cli]>=2.0.0",
    "pathlib>=1.0.1",
    "sqlglot>=30.17.0",
]

[project.scripts]
gufi-mcp = "gufi_mcp:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
